USE hr;
 
-- 1
ALTER TABLE locations CHANGE STREET_ADDRESS ADDRESS varchar(40) DEFAULT NULL;

SELECT ADDRESS FROM locations;

-- 2
ALTER TABLE regions CHANGE REGION_NAME REGION varchar(25) DEFAULT NULL;

-- 3

ALTER TABLE countries CHANGE COUNTRY_NAME COUNTRY varchar(40) DEFAULT NULL;