USE hr;

SELECT * FROM employees;

SELECT MAX(SALARY) FROM employees;
SELECT MAX(SALARY) - MIN(SALARY) FROM employees;

SELECT JOB_ID, AVG(SALARY) AS `salario medio` FROM employees
GROUP BY JOB_ID
ORDER BY `salario medio` DESC;

SELECT SUM(SALARY) AS `valor total salarios` FROM employees;
SELECT
	ROUND(MAX(SALARY), 2),
    ROUND(MIN(SALARY), 2),
    ROUND(SUM(SALARY), 2),
    ROUND(AVG(SALARY), 2)
FROM employees;

SELECT JOB_ID, COUNT(*) FROM employees
-- GROUP BY JOB_ID
-- HAVING JOB_ID = 'IT_PROG';
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS `Media` FROM employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG'
ORDER BY `Media` DESC;

SELECT DEPARTMENT_ID, AVG(SALARY) AS `Media Salarial`, COUNT(*) AS `Numero Funcs` FROM employees
GROUP BY DEPARTMENT_ID
HAVING `Numero Funcs` > 10;

UPDATE employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';

SELECT * FROM employees
WHERE CHAR_LENGTH(FIRST_NAME) >= 8;

